<?php

return [
    /*
    |--------------------------------------------------------------------------
    | THE DEFAULT SECTIONS (only used if not set manually)
    |--------------------------------------------------------------------------
    |
    */
    'bot_properties' =>
        [
            'age'=>5,
            'baseballteam'=>5,
            'birthday'=>5,
            'birthplace'=>5,
            'botmaster'=>5,
            'boyfriend'=>5,
            'build'=>5,
            'celebrities'=>5,
            'celebrity'=>5,
            'class'=>5,
            'email'=>6,
            'emotions'=>5,
            'ethics'=>5,
            'etype'=>5,
            'family'=>5,
            'favoriteactor'=>5,
            'favoriteactress'=>5,
            'favoriteartist'=>5,
            'favoriteauthor'=>5,
            'favoriteband'=>5,
            'favoritebook'=>5,
            'favoritecolor'=>5,
            'favoritefood'=>5,
            'favoritemovie'=>5,
            'favoritesong'=>5,
            'favoritesport'=>5,
            'feelings'=>5,
            'footballteam'=>5,
            'forfun'=>5,
            'friend'=>5,
            'friends'=>5,
            'gender'=>5,
            'genus'=>5,
            'girlfriend'=>5,
            'hockeyteam'=>5,
            'kindmusic'=>5,
            'kingdom'=>5,
            'language'=>5,
            'location'=>5,
            'looklike'=>5,
            'master'=>5,
            'msagent'=>5,
            'name'=>5,
            'nationality'=>5,
            'order'=>5,
            'orientation'=>5,
            'party'=>5,
            'phylum'=>5,
            'president'=>5,
            'question'=>5,
            'religion'=>5,
            'sign'=>5,
            'size'=>5,
            'species'=>5,
            'talkabout'=>5,
            'version'=>5,
            'vocabulary'=>5,
            'wear'=>5,
            'website'=>6,
        ],
    'category_groups' =>
        [
            'dev-testcases' => 1,
            'std-critical' => 2,
            'std-rating' => 7,
            'std-hello' => 2,
            'std-65percent' => 2,
            'std-atomic' => 2,
            'std-botmaster' => 3,
            'std-brain' => 2,
            'std-dictionary' => 4,
            'std-howto' => 4,
            'std-inventions' => 4,
            'std-gender' => 2,
            'std-geography' => 4,
            'std-german' => 4,
            'std-gossip' => 7,
            'std-knowledge' => 4,
            'std-lizards' => 4,
            'std-numbers' => 4,
            'std-personality' => 3,
            'std-pickup' => 2,
            'std-politics' => 4,
            'std-profile' => 3,
            'std-religion' => 4,
            'std-robot' => 4,
            'std-sports' => 4,
            'std-sales' => 7,
            'std-sextalk' => 2,
            'std-srai' => 2,
            'std-that' => 2,
            'std-suffixes' => 2,
            'std-turing' => 4,
            'std-yesno' => 2,
            'std-learn' => 7,
            'std-happybirthday' => 4,
            'std-horoscope' => 4,
            'std-howmany' => 2,
            'std-jokes' => 4,
            'std-knockknock' => 4,
            'std-yomama' => 4,
            'std-shutup' => 4,
            ]

];
